version: "3.9"

services:
  server:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    image: accessibilitymap-server
    container_name: accessibilitymap-go-server
    command: go run .
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - APP_ENV=development
    networks:
      - app-network
    expose: [8080]
  mongo:
    restart: always
    image: mongo:4.0
    container_name: accessibilitymap-mongo
    volumes:
      - ~/Volumes/accessibilitymap-mongo-4.0:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local
